import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 4,
  tables: [
    tableSchema({
      name: 'profiles',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'email', type: 'string' },
        { name: 'full_name', type: 'string', isOptional: true },
        { name: 'avatar_url', type: 'string', isOptional: true },
        { name: 'username', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'workspaces',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'owner_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'projects',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'workspace_id', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'is_archived', type: 'boolean' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'tasks',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'priority', type: 'string' },
        { name: 'project_id', type: 'string' },
        { name: 'assignee_id', type: 'string', isOptional: true },
        { name: 'created_by', type: 'string' },
        { name: 'due_date', type: 'number', isOptional: true },
        { name: 'completed_at', type: 'number', isOptional: true },
        { name: 'position', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'subtasks',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'title', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'is_completed', type: 'boolean' },
        { name: 'task_id', type: 'string' },
        { name: 'position', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'comments',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'content', type: 'string' },
        { name: 'task_id', type: 'string' },
        { name: 'author_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'tags',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'name', type: 'string' },
        { name: 'color', type: 'string' },
        { name: 'workspace_id', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'task_tags',
      columns: [
        { name: 'task_id', type: 'string' },
        { name: 'tag_id', type: 'string' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'workspace_members',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'workspace_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'role', type: 'string' },
        { name: 'joined_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'attachments',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'filename', type: 'string' },
        { name: 'file_path', type: 'string' },
        { name: 'file_size', type: 'number', isOptional: true },
        { name: 'mime_type', type: 'string', isOptional: true },
        { name: 'task_id', type: 'string' },
        { name: 'uploaded_by', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'time_entries',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'task_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'duration', type: 'number' },
        { name: 'start_time', type: 'number', isOptional: true },
        { name: 'end_time', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'activity_logs',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'entity_type', type: 'string' },
        { name: 'entity_id', type: 'string' },
        { name: 'action', type: 'string' },
        { name: 'changes', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'task_completions',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'task_id', type: 'string' },
        { name: 'completed_by', type: 'string' },
        { name: 'completed_at', type: 'number' },
        { name: 'completion_type', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'user_streaks',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'streak_type', type: 'string' },
        { name: 'current_count', type: 'number' },
        { name: 'longest_count', type: 'number' },
        { name: 'last_activity_date', type: 'number' },
        { name: 'streak_start_date', type: 'number' },
        { name: 'is_active', type: 'boolean' },
        { name: 'available_protections', type: 'number' },
        { name: 'used_protections', type: 'number' },
        { name: 'protection_reset_date', type: 'number' },
        { name: 'is_protected_today', type: 'boolean' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'daily_activities',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'activity_date', type: 'number' },
        { name: 'tasks_completed', type: 'number' },
        { name: 'tasks_created', type: 'number' },
        { name: 'total_tasks', type: 'number' },
        { name: 'completion_rate', type: 'number' },
        { name: 'active_time_minutes', type: 'number' },
        { name: 'habit_completions', type: 'number' },
        { name: 'streak_days', type: 'number' },
        { name: 'goals_achieved', type: 'number' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
    tableSchema({
      name: 'streak_protections',
      columns: [
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'user_id', type: 'string' },
        { name: 'streak_id', type: 'string' },
        { name: 'task_id', type: 'string', isOptional: true },
        { name: 'protection_date', type: 'number' },
        { name: 'protection_type', type: 'string' },
        { name: 'reason', type: 'string' },
        { name: 'available_protections', type: 'number' },
        { name: 'used_protections', type: 'number' },
        { name: 'metadata', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'synced_at', type: 'number', isOptional: true },
        { name: 'is_dirty', type: 'boolean' },
      ],
    }),
  ],
});